// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_bOpM_kjFEtBsiUthcsbZWldynQN8LoU',
    appId: '1:170867652760:web:18b07235922eff821638ed',
    messagingSenderId: '170867652760',
    projectId: 'read-quest-51cbb',
    authDomain: 'read-quest-51cbb.firebaseapp.com',
    storageBucket: 'read-quest-51cbb.firebasestorage.app',
    measurementId: 'G-G67CN2DTQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0bA3BZvx8q_tB5qV464AJWrNHMiLW6VA',
    appId: '1:170867652760:android:550215688b9278ad1638ed',
    messagingSenderId: '170867652760',
    projectId: 'read-quest-51cbb',
    storageBucket: 'read-quest-51cbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwPoUSx5PpeZtkzxXf41pIR1vzl9kbOms',
    appId: '1:170867652760:ios:3fac7bbde79ead651638ed',
    messagingSenderId: '170867652760',
    projectId: 'read-quest-51cbb',
    storageBucket: 'read-quest-51cbb.firebasestorage.app',
    iosBundleId: 'com.example.readQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwPoUSx5PpeZtkzxXf41pIR1vzl9kbOms',
    appId: '1:170867652760:ios:3fac7bbde79ead651638ed',
    messagingSenderId: '170867652760',
    projectId: 'read-quest-51cbb',
    storageBucket: 'read-quest-51cbb.firebasestorage.app',
    iosBundleId: 'com.example.readQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_bOpM_kjFEtBsiUthcsbZWldynQN8LoU',
    appId: '1:170867652760:web:ef93b7def5bdc63e1638ed',
    messagingSenderId: '170867652760',
    projectId: 'read-quest-51cbb',
    authDomain: 'read-quest-51cbb.firebaseapp.com',
    storageBucket: 'read-quest-51cbb.firebasestorage.app',
    measurementId: 'G-LJYYEHFBJN',
  );
}
